# Generated by Django 5.1.7 on 2025-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
