# Generated by Django 5.1.7 on 2025-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='leaderboard_images/')),
                ('project_name', models.CharField(max_length=100)),
                ('project_link', models.URLField()),
            ],
        ),
    ]
