# Generated by Django 5.1.7 on 2025-07-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_leaderboardmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='semester',
        ),
        migrations.AddField(
            model_name='customuser',
            name='session',
            field=models.CharField(choices=[('25-26', '25-26'), ('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22')], default=-1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('CST', 'Computer Science & Tech'), ('ET', 'Electrical'), ('MT', 'Mechanical'), ('CMT', 'Civil'), ('AUT', 'Automobile')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wing',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Graphics Design', 'Graphics Design'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Cybersecurity', 'Cybersecurity'), ('IT and Hardware Support', 'IT and Hardware Support')], max_length=100),
        ),
    ]
