# Generated by Django 5.1.7 on 2025-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customuser_semester_customuser_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='learning_materials/')),
                ('wing', models.CharField(choices=[('Programming', 'Programming'), ('Graphics Design', 'Graphics Design'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Cybersecurity', 'Cybersecurity'), ('IT and Hardware Support', 'IT and Hardware Support')], max_length=100)),
                ('content_link', models.URLField(blank=True)),
            ],
        ),
    ]
