# Generated by Django 5.1.7 on 2025-09-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='learning_thumbnails/'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='learning_videos/'),
        ),
    ]
