# Generated by Django 5.1.7 on 2025-09-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lessoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
